# Generated by Django 3.0.8 on 2020-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomplishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('hostingLink', models.URLField(blank=True)),
                ('githubLink', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('accomplishments', models.ManyToManyField(to='accomplishment.Accomplishment')),
            ],
        ),
    ]
