# Generated by Django 3.0.8 on 2020-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0001_initial'),
        ('openSource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensource',
            name='accomplishments',
            field=models.ManyToManyField(to='accomplishment.Accomplishment'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='githubLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opensource',
            name='hostingLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opensource',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
