# Generated by Django 3.0.8 on 2020-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('subTitle', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('scoring', models.CharField(max_length=70)),
            ],
        ),
    ]
