---
    - hosts: prod
      tasks:
        - name: Execute Deploy Script
          shell: ~/deploy_scripts/portfolio
          register: deploy_result
        - debug: msg="{{ deploy_result.stdout }}"